# user
member.login=SELECT * FROM member WHERE member_id = ?
member.insert=INSERT INTO member(member_id,password,name) VALUES(?,?,?)

# hotel
hotel.popular=SELECT hotel_id,hotel_name,location,image_path,min_price \
FROM hotel ORDER BY view_count DESC LIMIT 4

# Room
room.preview=SELECT room_id,room_name,price,image_path \
FROM room ORDER BY price DESC LIMIT 3